export enum USER_ROLES {
     SUPER_ADMIN = 'SUPER_ADMIN',
     ADMIN = 'ADMIN',
     USER = 'USER',
}
export const ROLE_GROUPS = {
     ALL: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
     ADMINS: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN],
     ADMINS_AND_USERS: [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN, USER_ROLES.USER],
     USERS: [USER_ROLES.USER],
} as const;
